### ISSUE TITLE
API for rescanning the browse paths

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode-cpptools-api#11]
Currently there is no way to detect changes to files in the browse paths outside the workspace folder.

One way to solve this would be to add file system watchers to browse paths outside the workspace folder, but that can be expensive. An alternative would be to have an API for customConfigurationProviders to force a rescan.

In our scenario, changes to paths outside the workspace folder often times happen due to a build, which if done via our extension, can trigger the rescan.

**Comment by sean-mcmanus** [comment]
Would a C_Cpp.RescanWorkspace command added to the C/C++ extension be okay? Is your extension able to just call that without adding a custom config API? VS has that command and we've thought about adding it.

Not sure if more file watchers would be better.

**Comment by sherryyshi** [comment]
It seems like that should work: https://stackoverflow.com/questions/41559471/is-it-possible-to-call-command-between-extensions-in-vscode

**Comment by sherryyshi** [comment]
Although it would be great if we can pass in a parameter that specifies the path to rescan, since our browse path list can be long and often times only a small portion of it would need to be rescanned. Although this is lower priority.

As for file system watchers, for our scenarios, you would definitely want to handle the events in batches, because lots of files can change/get created in a short period of time during a build.

**Comment by bobbrow** [comment]
Rescanning a workspace is usually pretty fast if most of the files have not changed.  I have a PR out to add a command to rescan the workspace.

**Comment by sherryyshi** [comment]
Awesome, thanks Bob!

**Comment by bobbrow** [comment]
Rescan workspace was released in cpptools version 0.24.0.
