### ISSUE TITLE
Lack of debugger extensibility

### ISSUE THREAD

**Issue by kagonzalez** [microsoft/vscode-cpptools-api#12]
From reading through this API's code and the vscode-cpptools extension code it is clear to me that this API only allows for the extension of the language server. If I am wrong can someone please point me in the correct direction, otherwise I would like to request this as a feature.
EDIT: I just read the NPM page for the API and see that it said that it was only "to provide IntelliSense" however I would still like to propose a similar debugger API.

**Comment by sean-mcmanus** [comment]
Yes, this repo is just for the language server extension. The debugger code is at https://github.com/microsoft/vscode-cpptools and https://github.com/microsoft/MIEngine . Can you file your request with more info on what API you want at https://github.com/microsoft/vscode-cpptools/issues/ ?

**Comment by kagonzalez** [comment]
Thank you for such a quick response, I will do just that.
