### ISSUE TITLE
No way to add mac framework paths

### ISSUE THREAD

**Issue by Mossop** [microsoft/vscode-cpptools-api#14]
As well as providing an includePath it would be useful to be able to provide framework paths on OSX.

**Comment by Mossop** [comment]
Oh it seems to just work if I stick it in the includePath?

**Comment by bobbrow** [comment]
Yes, that works.  We originally supported Mac Frameworks via the includePath before we added the `macFrameworkPath` property and that support still works.  Perhaps we should update the comment on the API.  Thanks for bringing this to our attention.

**Comment by bobbrow** [comment]
Comment is updated in 3.0.0
