### ISSUE TITLE
Differences between `SourceFileConfiguration` and `c_cpp_properties.json`...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode-cpptools-api#19]
hey there :wave:

as i continue to improve support for intellisense in [Particle Workbench](https://marketplace.visualstudio.com/items?itemName=particle.particle-vscode-pack), i'm noticing there are a few differences between what can be configured via the provider APIs (`CustomConfigurationProvider` and related) and what is supported via the standard `c_cpp_properties.json` configuration file.

specifically:
* `standard` vs. `cStandard` and `cppStandard` (briefly discussed [here](https://github.com/microsoft/vscode-cpptools-api/pull/10))
* `compileCommands` is not supported

what's the reasoning here? i ask b/c i need to generate much of the required info as part of my release process and want to target a stable, well-documented output format.

i'm also fuzzy on the UX around `c_cpp_properties.json` support for the `configurationProvider` field - does using this allow end-users to add _their own_ settings on top of what the provider sets? if so, are end-user settings merged or do they fully replace what is provided?

thanks :pray:

**Comment by bobbrow** [comment]
> yeah, i get that. how do you go about disambiguating `.h` files? 

For `.h` files we try to find a `.c` or `.cpp` file that includes it and then we ask you for the configuration for that file instead (since many providers don't know what to do with `.h`).

> and how does it work for `WorkspaceBrowseConfiguration` ([source](https://github.com/microsoft/vscode-cpptools-api/blob/master/api.ts#L234)) since `provideBrowseConfiguration()` and the newly added `provideFolderBrowseConfiguration()` don't expose file-level URIs...?

For WorkspaceBrowseConfiguration you would return a C++ standard if there are any C++ files in your project and a C standard otherwise.  For mixed language projects, you return a C++ standard.  What you send here determines whether the C++ STL is browseable or not.

> ah, ok. well, i'm actually trying to configure the entire project. my wrinkle is that configurations can change based on how the user has configured their project.

If the configurations change based on user interaction with the workspace (e.g. switching a configuration from "Debug" to "Release"), you call the `didChangeCustomConfiguration` and `didChangeCustomBrowseConfiguration` APIs to tell cpptools to discard the previously provided information and ask for it again.

**Comment by busticated** [comment]
@bobbrow thanks :pray:

> For .h files we try to find a .c or .cpp file that includes it and then we ask you for the configuration for that file instead (since many providers don't know what to do with .h). If we don't find a good match, we'll ask you for the configuration for the .h directly.

ah, that works :+1:

> For mixed language projects, you return a C++ standard.

sound good 👍 

> If the configurations change based on user interaction with the workspace (e.g. switching a configuration from "Debug" to "Release"), you call the didChangeCustomConfiguration and didChangeCustomBrowseConfiguration APIs to tell cpptools to discard the previously provided information and ask for it again.

yep, that's what i'm doing today. my point was that as we are exploring migrating to a `cmake` driven build system, it would be convenient to provide those configurations as `compileCommands` (aka `compile_commands.json`) while still using the provider API to supply configuration. otherwise, we'll essentially be translating from `compile_commands.json` to the format accepted via the provider API (`defines`, `includePaths`, etc) which seems redundant since you all already have that logic in place today.

but i guess that's better filed as a "feature request" so fwiw 🤗

**Comment by bobbrow** [comment]
If you are migrating to CMake, is your extension able to leverage the [CMake Tools](https://github.com/microsoft/vscode-cmake-tools) extension which already implements the configuration provider?  We recently became the maintainers of that extension and can work with you to make sure your stuff continues to configure properly if you want to try that route.

**Comment by busticated** [comment]
ah, interesting! i'll definitely take a look :+1:

one tricky bit for us is that we'd need to support both old _and_ new build systems in order to facilitate building older releases 😬

**Comment by bobbrow** [comment]
Is there anything left from this issue that needs to be addressed?

**Comment by busticated** [comment]
nope!
