### ISSUE TITLE
SourceFileConfiguration.intelliSenseMode doesn't allow "${default}" value

### ISSUE THREAD

**Issue by alexcamposruiz** [microsoft/vscode-cpptools-api#22]
The field `intelliSenseMode` in `SourceFileConfiguration` forces developers to pick one of `"msvc-x86" | "msvc-x64" | "gcc-x86" | "gcc-x64" | "clang-x86" | "clang-x64"`, when in most cases you would want to use whatever the default value for a given platform is.

This field should be optional or else "${default}" should be one of the allowed values.

**Comment by sean-mcmanus** [comment]
The API is meant to be used by build system providers which should have knowledge of the target platform/compiler. Correct IntelliSense info can't be provided unless the compiler info (hence intelliSenseMode) is also known. Your extension should be able to check the OS and set default values if you want (ideally you'd check for the exact compiler info like the CMake Tools extension does). The C/C++ extension has the concept of a "${default}", but only for c_cpp_properties.json items and its effect is to pull the value from the C_Cpp.default.* setting. With a configurationProvider set, that takes precendence.

compilerPath is optional, but in that case, it is expected that the includePath/defines/intelliSeseMode would be set directly by the configurationProvider.

**Comment by alexcamposruiz** [comment]
In my extension I simply want to add a few directories to the `includePath`'s. I want to keep everything else unmodified. What would be the best way to do that?

I used `${default}` everywhere I could (compilerPath, as the first element in includePath, etc) and it seems to work.

**Comment by sean-mcmanus** [comment]
The configuration provider API isn't designed for adding configuration settings to settings provided by other mechanisms (compileCommands, c_cpp_properties, etc.). From what I'm seeing the code "${default}" shouldn't work when passed via a config provider -- see https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/client.ts#L2014 (the resolution of "${default} happens at https://github.com/microsoft/vscode-cpptools/blob/release/Extension/src/LanguageServer/configurations.ts#L547 and only overwrites the "${default}" in c_cpp_properties.json with the corresponding C_Cpp.default.* setting ). In the language server process (closed source part), if no compilerPath is set with a config provder, then we will fallback to the whatever compiler info we auto-detect, but the intelliSenseMode is used in that auto-detection process.

@bobbrow @andreeis might have more to say.

**Comment by alexcamposruiz** [comment]
My first attempt was to rely on the `includePath` parameter by updating c_cpp_properties.json from my extension, but that proved quite complicated when that file doesn't exist. I tried invoking the vscode-cpptools-extension command that generates that file and then modify it, but I have no way of knowing when the command finishes, so my extension can't know when it's safe to read and write it.

That's when I learnt about this repo and the `ConfigurationProvider` approach. I was hoping I could provide the includePath and leave everything set to the default (that is, whatever the vscode-cpptools extension does when that configuration parameter is not specified anywhere).

What would you recommend when an extension simply wants to add to the include paths?

**Comment by sean-mcmanus** [comment]
We have a C_Cpp.AddToIncludePath command that we register internally -- you might be able to expose a similar API similar externally so it could be called from your extension (i.e. if you took a dependency on the cpptools extension and called an API or command from it). But that only works if a user is using includePath from c_cpp_properties.json (and not compileCommands or configurationProvider).

This vscode-cpptools-api isn't intended for the purpose of adding includePath.

**Comment by Colengms** [comment]
With this PR: https://github.com/microsoft/vscode-cpptools-api/pull/28 , intelliSenseMode has been made optional.  Once the next update is published, you can leave the intelliSenseMode field undefined.  If compilerPath (and compilerArgs) are provided, they will be used to infer the appropriate IntelliSenseMode (with cpptools >= 1.1.0).  Otherwise, it will fall back to defaults.  Ideally, any custom config provider based on a build system can provide whatever command line the build system uses to compile the file, and cpptools should do the right thing.
