### ISSUE TITLE
Understanding SourceFileConfiguration

### ISSUE THREAD

**Issue by tanshihaj** [microsoft/vscode-cpptools-api#29]
I'm working with `vscode-cpptools-api` to make vscode support some custom build system and it seems I don't understand how to use api.

For example I have a file in project `/Users/zaripov-kamil/blah/plumbus/main.cpp` that compiles fine with command `clang++ -c -o /Users/zaripov-kamil/blah/plumbus/main.cpp.o /Users/zaripov-kamil/blah/plumbus/main.cpp -I/Users/zaripov-kamil/blah -DSOMEDEF=1 -std=c++17 ...`. So I fill SourceFileConfiguration in `provideConfigurations` as following:

```javascript
{
  "includePath": [
    "/Users/zaripov-kamil/blah"
  ],
  "defines": [
    "SOMEDEF=1"
  ],
  "intelliSenseMode": "clang-x64",
  "standard": "c++17",
  "compilerPath": "/usr/bin/clang++",
  "compilerArgs": [
    "-c",
    "-o",
    "/Users/zaripov-kamil/blah/plumbus/main.cpp.o",
    "/Users/zaripov-kamil/blah/plumbus/main.cpp",
    "-std=c++17",
    "...",
  ]
}
```
But it seems that cpptoos tries to compile `/Users/zaripov-kamil/blah/plumbus/main.cpp` without includes and defines form SourceFileConfiguration: https://bit.ly/3mh25pi (part of output from cpptools).

How should I correctly fill SourceFileConfiguration knowing compile command?

**Comment by sean-mcmanus** [comment]
The line "/Users/zaripov-kamil/blah/plumbus/main.cpp:1:10: fatal error: 'include/cli..." looks suspicious.

@Colengms Do you have any thoughts?

**Comment by Colengms** [comment]
Hi @tanshihaj .  Could you try omitting the source file name from the compiler args?  I believe that is implicit, and we're not expecting it (so are not stripping it out in this scenario).  The compiler args are used to query the compiler for default system includes and default defines.  We should already be stripping out other args that might interfere with querying the compiler, such as `-o <filename>`.

**Comment by tanshihaj** [comment]
Yes, @Colengms was right, this problem solved
