### ISSUE TITLE
Move vscode-jsonrpc from devDependencies to the dependencies

### ISSUE THREAD

**Issue by tanshihaj** [microsoft/vscode-cpptools-api#30]
When I add `vscode-cpptools` to my package dependencies, plugin compilation fails since there is no `vscode-jsonrpc` package dependency in `package.json` of `vscode-cpptools` although uses it here: https://github.com/microsoft/vscode-cpptools-api/blob/c9f413d8fe33f52ea67e48b6ce4f1af52ed075f4/api.ts#L8

So plugin developers have to add both `vscode-cpptools` and `vscode-jsonrpc` if they want to use `vscode-cpptools` (for example https://github.com/wpilibsuite/vscode-wpilib/blob/721ce3e4c699ee2ff1f1de1ddf0ae87f74411613/vscode-wpilib/package.json#L475-L476).

It would be more convenient if you will move `vscode-jsonrpc` (https://github.com/microsoft/vscode-cpptools-api/blob/master/package.json#L14) to the "dependencies".

**Comment by sean-mcmanus** [comment]
Thanks for letting us know. I have a potential fix at https://github.com/microsoft/vscode-cpptools-api/pull/31 .
