### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools-api#32]
See https://github.com/github/renaming#later-this-year

**Comment by sean-mcmanus** [comment]
@bobbrow I don't seem to have permissions to change this.

**Comment by bobbrow** [comment]
I don't either. I am trying to find an admin to help us get permissions.

**Comment by sean-mcmanus** [comment]
Oh, that's odd. I thought you created this GitHub repo, right? It shows you were the first to commit changes. Maybe the accounts https://github.com/msftgits and https://github.com/microsoftopensource maintained admin privileges due to the manner in which the repo was created.

**Comment by bobbrow** [comment]
I'm not sure what happened, but our team has admin privileges now.
