### ISSUE TITLE
discarding invalid SourceFileConfigurationItem

### ISSUE THREAD

**Issue by github0null** [microsoft/vscode-cpptools-api#39]
Can someone help me?

I added CustomConfigurationProvider to provide source file configuration, but it always prompt this is invalid configuration

**I complete the registration with the following code:**

```ts
getCppToolsApi(Version.v2).then((api) => {

    if (!api) {
        GlobalEvent.emit('msg', newMessage('Error', `can't get C/C++ intellisense provider api !`));
        return;
    }

    this.cppToolsApi = api;

    if (api.notifyReady) {
        api.registerCustomConfigurationProvider(this);
        api.notifyReady(this);
    } else {
        // Inform cpptools that a custom config provider will be able to service the current workspace.
        api.registerCustomConfigurationProvider(this);
        api.didChangeCustomConfiguration(this);
    }
});
```
When I provide the configuration to the source file, it gets the following error, no matter what I do, it always tells me this is an invalid configuration, even if I use empty config.

![image](https://user-images.githubusercontent.com/43022536/145591892-af9825b7-48c6-4e91-84d5-deaa0d2209d8.png)

**Comment by sean-mcmanus** [comment]
With Version.v2, configuration.intellSenseMode and configuration.standard are both required to be strings -- the API was changed to make those fields options with Version.v5.
