### ISSUE TITLE
Cambio

### ISSUE THREAD

**Issue by Vichugo1995** [microsoft/vscode-cpptools-api#49]
git reset [-q] [<tree-ish>] [--] <pathspec>…
​ git reset [-q] [--pathspec-from-file=<file> [--pathspec-file-nul]] [<tree-ish>]
 git reset (--patch | -p) [<tree-ish>] [--] [<pathspec>…​]
 git reset [--soft | --mixto [-N] | --duro | --combinar | --mantener] [-q] [<confirmar>]

**Comment by Vichugo1995** [comment]
>confirma

**Comment by sean-mcmanus** [comment]
Your post doesn't make any sense.
