### ISSUE TITLE
Use URI rather then string for file URI

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode-cpptools-api#6]
As discussed in https://github.com/Microsoft/vscode-cpptools/issues/2228, the URI for the file should be a URI rather then a string, since the API receives the file as a URI. The issue in the other repo said this would be something fixed in 2.0, but looking at 2.0 it wasn't fixed. I'm posting this as an issue here so maybe it gets fixed for 3.0.

**Comment by bobbrow** [comment]
Bummer.  That issue was closed and I didn't move the problem over to a new one so I missed this.  If node lets me replace a version, I might redo v2 and add this in instead of jumping to 3.0.

**Comment by bobbrow** [comment]
I unpublished 2.0.0.  The new one will be 2.1.0.

**Comment by bobbrow** [comment]
I suppose it was unnecessary to unpublish.  I decided to make the field an "or" type so that you can assign it either way.

**Comment by bobbrow** [comment]
That way it wouldn't warrant a full API version update.
