### ISSUE TITLE
 error TS1308: 'await' expression is only allowed within an async function

### ISSUE THREAD

**Issue by matthewfcarlson** [Microsoft/vscode-cpptools-api#8]
I'm getting an error when including the default sample code in my extensions activation event. I've checked I'm targeting ES6. I can see you've included the async keyword in your code so I'm a little stumped why.

This is the line
```typescript
let api: CppToolsApi | undefined = await getCppToolsApi(Version.v2);
```

**Comment by bobbrow** [comment]
What is the error?  The API is exported as a Promise.  You don't need to use async/await if you would rather use promises directly.

```ts
export declare function getCppToolsApi(version: Version): Promise<CppToolsApi | undefined>;
```

**Comment by matthewfcarlson** [comment]
It looks like the activate function on the module needed to be async as well. Sorry still a newbie at TypeScript.
