### ISSUE TITLE
Update `standard` into `cStandard` and `cppStandard`

### ISSUE THREAD

**Issue by xVanTuring** [Microsoft/vscode-cpptools-api#9]
Please update `standard` into `cStandard` and `cppStandard`
```
// https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md
"cStandard": "c11",
"cppStandard": "c++17",
```
https://github.com/Microsoft/vscode-cpptools-api/blob/c8845b03e76c61a0cb40ef9d308cef142a3d8bfb/out/api.d.ts#L118

**Comment by bobbrow** [comment]
Based on discussion in the linked pull request, I believe this issue may now be closed.  Please let me know if there is anything further we need to solve here.
